repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_docs
        args:
            - --args=--config=.terraform-docs.yml
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terragrunt_providers_lock
        stages:
          - manual # note: this step is very expensive, so you need to invoke it explicitly via `--hook-stage manual`
        args:
          - --args=-platform=darwin_arm64
          - --args=-platform=darwin_amd64
          - --args=-platform=linux_amd64

      - id: terraform_tflint
        files: ^kit/
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl # share a single tflint config file for all modules

      # tfupdate hooks for aligning terraform and provider versions
      # aligning versions helps build performance becuase there's less providers to download/cache across all our modules
      - id: tfupdate
        name: tfupdate terraform
        args:
          - --args=terraform
          - --args=--version ">= 1.0"

      - id: tfupdate
        name: tfupdate hashicorp/time
        args:
          - --args=provider hashicorp/time
          - --args=--version "0.11.1"

      - id: tfupdate
        name: tfupdate hashicorp/azurerm
        args:
          - --args=provider hashicorp/azurerm
          - --args=--version "3.116.0"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/azuread
        args:
          - --args=provider hashicorp/azuread
          - --args=--version "3.0.2"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/aws
        args:
          - --args=provider hashicorp/aws
          - --args=--version "5.65.0"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/random
        args:
          - --args=provider hashicorp/random
          - --args=--version "3.6.0"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/time
        args:
          - --args=provider hashicorp/time
          - --args=--version "0.11.1"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/null
        args:
          - --args=provider hashicorp/null
          - --args=--version "3.2.2"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

      - id: tfupdate
        name: tfupdate hashicorp/local
        args:
          - --args=provider hashicorp/local
          - --args=--version "2.5.1"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"


      - id: tfupdate
        name: tfupdate integrations/github
        args:
          - --args=provider integrations/github
          - --args=--version "5.42.0"
          - --args=--ignore-path "kit/.*/buildingblocks/.*"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: "^compliance/"
