repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.4
    hooks:
      - id: terraform_docs
        args:
            - --args=--config=.terraform-docs.yml
      - id: terraform_fmt
      - id: terragrunt_fmt
      - id: terragrunt_providers_lock
        stages:
          - manual # note: this step is very expensive, so you need to invoke it explicitly via `--hook-stage manual`
        args:
          - --args=-platform=darwin_arm64
          - --args=-platform=darwin_amd64
          - --args=-platform=linux_amd64
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude: "^compliance/"
