apiVersion: v1
kind: meshWorkspace
metadata:
  name: m25-online-banki
spec:
  displayName: M25 Online Banking
  tags:
    environment: # todo: the environment tag values are not aligned between likvid-demo and meshcloud-dev
    - dev
    - qa
    - prod
    BusinessUnit:
    - M25
    SecurityContact:
    - banking@m25.example.com
    # todo: landingzone clearance is missing
