apiVersion: v1
kind: meshWorkspace
metadata:
  name: sap-core-platform
spec:
  displayName: SAP Core Platform
  tags:
    environment: # todo: the environment tag values are not aligned between likvid-demo and meshcloud-dev
    - dev
    - qa
    - prod
    BusinessUnit:
    - IT
    SecurityContact:
    - sap-core-platform@likvid.meshcloud.io

    # todo: landingzone clearance is missing
