---
############################################
# These are the rules used for             #
# linting all the yaml files in the module #
############################################
extends: default
rules:
  braces:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  line-length:
    max: 400
