# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "meshcloud-tf-states"
    prefix = "likvid-cloudfoundation/foundations/likvid-prod/platforms/ske/infra/cluster-issuer"
  }
}
