name: build
on:
  pull_request:
    branches:
    - prod
    - dev

jobs:
  prod:
    if: ${{ github.base_ref == 'prod' }}
    uses: ./.github/workflows/build-workflow.yml
    secrets: inherit
    with:
      foundation: likvid-prod
      client-id: d009bc1c-9076-4e4e-8cdf-967bc25f5dcf # see azure/bootstrap output
      tenant-id: 703c8d27-13e0-4836-8b2e-8390c588cf80
      subscription-id: 9809209b-869e-4f5c-8d86-c8b71294153f
  dev:
    if: ${{ github.base_ref == 'dev' }}
    uses: ./.github/workflows/build-workflow.yml
    secrets: inherit
    with:
      foundation: likvid-dev
      client-id: 9db76cb2-5586-48cf-bdfc-6db6732338b5 # see azure/bootstrap output
      tenant-id: 703c8d27-13e0-4836-8b2e-8390c588cf80
      subscription-id: d2882536-7b9b-4537-ac9a-840d116388a0