on:
  workflow_call:
    inputs:
      foundation:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.foundation }}
    env:
      TERRAGRUNT_TFPATH: tofu
      # required to enable for azurerm backend, the azurerm provider seems to be fine without these two keys
      ARM_CLIENT_ID: ${{ vars.azure_client_id }}
      ARM_USE_OIDC: true

      # required for the github deployment
      GITHUB_APP_PEM_FILE: ${{ secrets.LIVKID_GITHUB_APP_PEM_FILE }} # note: this environment secret must be set up manually on the github repo
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-nix-shell
        with:
          prepare_terraform: true

      - uses: meshcloud/setup-collie@main


      # TODO GCP
      # - name: Setup gcloud auth
      #   if: ${{ inputs.platform == 'gcp' }}
      #   id: 'auth'
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     service_account: '${{ vars.gcp_service_account }}' # sourced from gh environment variable
      #     workload_identity_provider: '${{ vars.gcp_workload_identity_provider }}'

      - name: Setup az auth
        if: ${{ inputs.platform == 'azure' }}
        uses: azure/login@v2
        with:
          client-id: ${{ vars.azure_client_id }}
          tenant-id: ${{ vars.azure_tenant_id }}
          subscription-id: ${{ vars.azure_subscription_id }}

      # TODO AWS
      # - name: Setup aws auth
      #   if: ${{ inputs.platform == 'aws' }}
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: eu-central-1
      #     role-to-assume: ${{ vars.aws_iam_role }}
      #     role-session-name: github-actions-${{ github.run_id }}

      - name: terraform plan
        run: |
          collie foundation deploy ${{ inputs.foundation }} --platform ${{ inputs.platform }} -- plan -lock=false -detailed-exitcode

      - name: run tests
        run: |
          collie foundation test ${{ inputs.foundation }} --platform ${{ inputs.platform }}
