name: build
on:
  pull_request:
    branches:
    - main

jobs:
  prod:
    if: ${{ github.base_ref == 'main' }}
    uses: ./.github/workflows/build-workflow.yml
    secrets: inherit
    with:
      foundation: likvid-prod
      client-id: d009bc1c-9076-4e4e-8cdf-967bc25f5dcf # see azure/bootstrap output
      tenant-id: 703c8d27-13e0-4836-8b2e-8390c588cf80
      subscription-id: 9809209b-869e-4f5c-8d86-c8b71294153f
