name: build
on:
  workflow_dispatch:

  push:
    branches:
      - "main"

  pull_request:
    branches: [ main ]

  merge_group:

jobs:
  platforms_plan:
    name: platforms plan
    uses: ./.github/workflows/build-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: false # don't cancel other matrix jobs if one fails
      matrix:
        foundation: [likvid-prod]
        platform: [azure, aws, gcp]
    with:
      foundation: ${{ matrix.foundation }}
      platform: ${{ matrix.platform }}
      action: plan

  platforms_test:
    name: platforms test
    uses: ./.github/workflows/build-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        foundation: [likvid-prod]
        platform: [azure] # todo: aws, gcp
    # ensure only one test job runs at a time to avoid terraform state clobbering each other (tests use shared names for resources)
    concurrency:
      group: ${{ matrix.foundation }}-${{ matrix.platform }}
      cancel-in-progress: false
    with:
      foundation: ${{ matrix.foundation }}
      platform: ${{ matrix.platform }}
      action: test
  meshStack:
    uses: ./.github/workflows/meshStack-workflow.yml
    secrets: inherit
    strategy:
      fail-fast: false # don't cancel other matrix jobs if one fails
      # unfortunately we don't have a deploy user for cloud foundry right now, if we want to add it we can
      # add individual matrix entries with "include:" attribute
      matrix:
        foundation: [likvid-prod]
        #platform: [aws, azure, gcp]
    with:
      foundation: ${{ matrix.foundation }}
      #platform: ${{ matrix.platform }}

  docs:
    uses: ./.github/workflows/docs-workflow.yml
    needs: meshStack
    secrets: inherit
    strategy:
      fail-fast: false # don't cancel other matrix jobs if one fails
      matrix:
        foundation: [likvid-prod]
    with:
      foundation: ${{ matrix.foundation }}

  publish:
    name: deploy docs
    if: github.ref == 'refs/heads/main' # only deploy if we're on main branch
    needs:
      - docs # this will depend on all jobs of the matrix
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: download docs-likvid-prod artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-likvid-prod
          path: './'

      - name: setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: deploy to GitHub Pages
        uses: actions/deploy-pages@v4
