on:
  push:
    branches:
      - prod

name: pr-in-collie-hub

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.MESHCLOUD_ORG_GH_APP_ID }}
          private_key: ${{ secrets.MESHCLOUD_ORG_GH_APP_ID }}

     - name: Checkout collie-hub repo
        uses: actions/checkout@v4
        with:
          repository: meshcloud/collie-hub
          token: ${{ steps.create_token.outputs.token }}

      - name: copy kits azure
        run: |
          cp -r likvid-cloudfoundation/kit/azure kit/azure

      - name: Create Pull Request in collie-hub repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.create_token.outputs.token }}
          commit-message: "feature: update azure kits from latest prod build"
          committer: GitHub Actions <github-actions@meshcloud.io>
          signoff: false
          branch: feature/update-collie-kits
          base: main
          delete-branch: true
          title: "[latest likvid kits] update latest kits from likvid-cloudfoundation"
          body: |
            The latest kits from likvid-cloudfoundation builds on the prod branch.
            - This PR is updated automatically with changes, until merged
          draft: false
