name: pr-in-collie-hub
on:
  pull_request:
    branches:
      - prod

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Checkout collie-hub repo
        uses: actions/checkout@v4
        with:
          path: hub
          repository: meshcloud/collie-hub
          ssh-key: ${{ secrets.COLLIE_HUB_KEY }}

      # TODO: its only for azure yet but it will be a similar workflow for AWS/GCP
      - name: Copy kits from likvid-cloudfoundation to collie-hub
        run: |
          rsync -av --exclude='*.tftest.hcl' kit/azure hub/kit/
          ls hub/kit/azure
          cd hub
          git add *
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "feature: Latest changes from likvid-cloudfoundation prod branch"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: hub
          ssh: true
          repository: meshcloud/collie-hub
          branch: "feature/auto-backporting"
