on:
  workflow_call:
    inputs:
      foundation:
        required: true
        type: string
      client-id:
        required: true
        type: string
      tenant-id:
        required: true
        type: string
      subscription-id:
        required: true
        type: string

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      TERRAGRUNT_TFPATH: tofu
      ARM_CLIENT_ID: ${{ inputs.client-id }} # export this for platform.hcl
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Setup az login
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.client-id }}
          tenant-id: ${{ inputs.tenant-id }}
          subscription-id: ${{ inputs.subscription-id }}

      - uses: actions/checkout@v4

      - uses: meshcloud/setup-collie@main

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-23.11:nixpkgs-unstable=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: default.nix

      - name: create terraform cache
        run: |
          dir=${{ runner.temp }}/.terraform.d/plugin-cache
          mkdir -p $dir # create terraform plugin cache
          echo "TF_PLUGIN_CACHE_DIR=$dir" >> $GITHUB_ENV

      - name: collie info
        run: collie info

      - name: Build and Update Documentation
        run: |
          collie foundation docs ${{ inputs.foundation }} --update --build --verbose --debug

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "foundations/${{ inputs.foundation }}/.docs/docs/.vuepress/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
