name: docs
on:
  push:
    branches:
      - main

jobs:
  prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/docs-workflow.yml
    with:
      foundation: likvid-prod
      client-id: 11a89d3c-4fe7-4d94-bcee-c257f7a33009 # see azure/bootstrap output
      tenant-id: 703c8d27-13e0-4836-8b2e-8390c588cf80
      subscription-id: 9809209b-869e-4f5c-8d86-c8b71294153f
    secrets: inherit
